language: python
dist: bionic
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - sudo apt-get update
  - pip install -U pip
  - pip install -U pytest
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run test_files
script:
  - pytest
